src/.vuepress/config.js
src/ges/0002-OeRH.md
src/ges/0003-microeconomia.md
src/ges/0005-fichas.md

já fiz o queria hoje, boas noites

---

src/.vuepress/config.js
src/ges/0002-OeRH.md
src/prog/0001-labs.md

labs do tomas

---

src/.vuepress/config.js
src/acomp/0003-PB3.md

Problemas 3

---

src/acomp/0003-PB3.md

ex5 by o teu maior amor

---

src/ges/0004-IF.md

A rafela é burra e não sabe escrever

---

src/acomp/0003-PB3.md

EX5 do martim, ele quiz mudar

---

src/.vuepress/config.js
src/ges/0002-OeRH.md
src/ges/0003-microeconomia.md
src/ges/0006-testes.md

está aqui, bom estudo #BonsDias #EnfiaODedoNoCu

já está aqui, deves estar com o fogo no cu xD

---

src/ges/0004-IF.md

mais um e ainda não é o ultimo

---

src/acomp/labs.md

Tô impressionado com essa mina
Sua boca está me insinuando
Contemplo a projeção divina
Me elucida me amando
Me faz sentir calafrios
Como as estações (me faz sentir calafrios, me faz sentir calafrios)
Transcende a brisa do vento e suas vibrações
Foram pouco os minutos pra conhecer
A química bateu, a gente ficou
Eu moro na favela, ela Zona Sul
É aí que o favelado se apaixonou
A peça fundamental que falta em mim
Sei que vou levar enquadro quando for lá
Deixa acontecer naturalmente
Oh mulher que me deixa na ponta do pé
Anormal, ela suga a cabeça do pau
Ejaculei, meu pipi começou a chorar
Disse que com seus lábios adorou dialogar (vai Sati)
Oh-oh-oh-oh
oh mulher que me deixa na ponta do pé
Anormal, ela suga a cabeça do pau
Ejaculei, meu pipi começou a chorar
Disse que com seus lábios adorou …

exercicio de casa lab 2

---

src/.vuepress/config.js
src/acomp/0007-PB4.md

EX2 DE PB4

---

src/acomp/0001-RN.md

Update na tua prima

---

src/mo/0007-momento-angular.md

falta adicionar cenas mas depois fazes tu sua escrava

tá aqui p*

---

src/mo/0003-simetrias-leis-conservacao.md
src/mo/0007-momento-angular.md

olá rita
mais um dia mais uma merda de MO, o que falta são basicamente demonstrações

adicionei umas cenas, mas vê TUDO

---

src/acomp/0009-Lab3.md

Não sei meter imagens, depois preciso que me ensines.

Lab 3 de acomp de sexta-feira

---

src/acomp/0004-Comp.md

olá, espero que o passeio tenha sido bom!!
vah estudar!!

foi só um exemplo com pilha

---

src/.vuepress/config.js
src/ges/0009-Cap5.md

não acabei o capitulo 5, porque isto é uma merda

oi darling

---

src/.vuepress/config.js
src/mo/0009-Ondas.md

desculpa bebe não me aptece

---

src/cdi-ii/0004-Exams.md

merdas de cdi

---

src/ges/0009-Cap5.md

hot tub streams são conteudos de muita qualidade

---

src/ges/0009-Cap5.md

Encontrei o sitio daquele pau de antes

---

src/ges/0010-Cap6.md

acrescentei umas cenas que faltavam

ola ola boneca

---

src/ges/0009-Cap5.md

Corrected small mistake in the "Inflação e taxas reais"

Corrected mistake
